eveseat/docs

docs/admin_guides/seat_supervisor.md

add supervisor 3 dependency and provide instructions for CentOS user in order to help them to update their package.

update documentation about supervisor monitoring

---

docs/development/general.md
docs/development/package_development.md

Add a section dedicated to good practice in third party package development as discussed early this winter.

add good practices section into package development

---

docs/seat_api/eve_api_keys.md

Provide documentation to eveseat/api#6

add duplicate key error to api

---

docs/installation_guides/quick_install.md

Thanks to @herpaderp for its quick how-to movie :)

Improve quick-install

---

docs/guides/installation/ubuntu.md

fix some typo

---

docs/guides/configuration/other.md
docs/guides/installation/centos6.md
docs/guides/installation/centos7.md
docs/guides/installation/debian.md
docs/guides/installation/installation.md
docs/guides/installation/ubuntu.md

depends on eveseat/console#21
depends on eveseat/installer#6
depends on eveseat/scripts#18

rename sde command to uniformize console

---

docs/guides/admin/docker.md
docs/guides/installation/basic_installation/esi.md
docs/guides/installation/basic_installation/traefik.md

* writing v1 of Traefik documenation
* fixed a funny if/of spelling misstake in admin/docker.md
* fixed inconsistency in /basic_installation/esi.md

Traefik Documentation

---

docs/guides/installation/basic_installation/apache.md
docs/guides/installation/basic_installation/nginx.md
mkdocs.yml

`Webserver` and assimiled chapter are actually loosing people in the walkthrought as it have nothing to do with "basic installation".
Switch them to an Extra section and highlighting the WIP thing until further review

moving "tips" stuff into extra section waiting for a review

---

docs/guides/installation/manual_installation/ubuntu.md

Changed <Directory /var/www/seat/> to <Directory /var/www/seat/public> in the example apache config file.

Added public directory to config file

---

docs/upgrading/from_seat_2_0.md

refer to the Requirements section instead of heaving to maintain requirements in two pages

Requirements in one place

---

docs/installation/webservers/apache.md
mkdocs.yml

* Added Apache Guide for Ubuntu 16.x
* Added Placeholder for Docker installation

Apache Guide

---

docs/installation/basic_installation.md

* fixing broken links
* added more details to next steps such as
** ESI configuration
** admin link creation

Basic Installation Update

---

docs/installation/basic_installation.md

Use mkdocs way to create an internal documentation link using bottom
references.
https://github.com/mkdocs/mkdocs/commit/78ee87cc2e64c2fa2418311903d64166b26f237c#diff-3a44f918234d90d4dc92e6bd92f3d859R109

fix(links): Attempt to fix internal linking using direct file reference

---

docs/about/contact.md
docs/admin_guides/role_based_access_control.md
docs/community_packages.md
docs/index.md
docs/troubleshooting.md

Updated docs:
Frontpage/index: fixed spelling mistakes
Role-based access control: added more details about limitations without plugin
Troubleshooting: fixed spelling mistakes
Community packages (plugins): added a few steps to generic package installation to reduce issues
Contact page: reformulated and corrected link to new forum post for SeAT 3.x

Updated docs

---

docs/community_packages.md

Update to include WHTools as a community package.

Update to include WHTools as a community package.

---

docs/developer_guides/developer_installation.md

Update docker install step 4

---

docs/admin_guides/scaled_deployments.md
mkdocs.yml

Add deprecation notice to horizontal scaling guide.
Also because I noticed, update the copyright in mkdocs.

Minor updates

---

docs/installation/manual/ubuntu.md

Before: They should also share be the same password.
After: They should also not have the same password.

Correction: root and db password.

---

docs/troubleshooting.md

Adding .ENV parameter as it is mentioned in Support multiple times.

Include the COMPOSER_MEMORY_LIMIT parameter

---

docs/installation/docker_installation.md

https://i.redd.it/vflyausf5zp11.jpg

Some typos

---

docs/community_packages.md

Clarify the file location and variable to install packages

Add location of where to install packages

---

docs/installation/docker_installation.md
docs/installation/manual_installation.md

Minor changes to a couple of lines.
NGINX script warning to be clearer it is a script and not a config file.
Docker install, don't advise to access over IP as this wont work with traefik (SNI required)

Minor Rewording

---

docs/community_packages.md

Made it more clear that the commands need to be run as the webserver user to keep permission intact.

Update community_packages.md with sudo command and a new maintained package

---

docs/community_packages.md

Add seat-rat module

---

docs/community_packages.md

https://github.com/recursivetree/seat-pushx-blamer
https://www.reddit.com/r/Eve/comments/ttnou0/announcing_seatpushxblamer/

Add the seat-pushx-blamer plugin to the list of community packages

---

docs/styling.md

Docker-compose.override.yml not -override

Correct file name

---

docs/community_packages.md

I've updated and fixed the helm charts for v4, and will maintain for the foreseeable future

change maintainer for helm

---

docs/upgrading/general.md

Quick fix sorry, probably my fault

Remove duplicate update command

---

docs/developer_guides/developer_installation.md
docs/developer_guides/development_tips.md
docs/developer_guides/notifications_implementation.md
docs/developer_guides/package_development.md
docs/developer_guides/seat_api.md
docs/developer_guides/updating_plugins.md
mkdocs.yml

* It started as an update to the notifications implementation page to reflect the refactors for seat 5
* I ended up improving and updating the rest of the developer documentation too.

Update developer docs

---

docs/installation/manual_installation_5.md
mkdocs.yml

This time with clean commits :)
I basically copied over the instructions from seat 4, and tested them in a ubuntu docker container.
The only major changes required were the php versions, plus enabling a few services here and there.

Seat 5 bare install instructions

---

docs/upgrading/from_seat_4_0/bare_metal.md

I basically followed the seat `3.x` -> `4.x` instructions and adapted them where necessary

seat 5 bare upgrade instructions

---

docs/configuration/esi_configuration.md
docs/developer_guides/notifications_implementation.md
docs/upgrading/from_seat_4_0/bare_metal.md
docs/upgrading/from_seat_4_0/docker.md

- A few more docs fixes, especially related to the docs still referring to 5.0.x instead of master

More docs fixes

---

docs/installation/old_versions/docker_installation_seat_4.md
docs/upgrading/from_seat_3_0/docker.md

- point seat 4 installation instructions to the seat 4 branch of seat-docker

point seat 4 installation instructions to the seat 4 branch

---

docs/upgrading/from_seat_4_0/docker.md

Instruct users to download the correct files when upgrading.

download the correct files when upgrading

---

docs/installation/manual_installation.md
docs/installation/requirements.md

Our docs mention you can also use MySQL, but in fact it is not compatible with SeAT. This PR removes any mentions of MySQL being compatible with SeAT.

State that only mariadb is compatible with seat

---

docs/upgrading/from_seat_4_0/docker.md

This does only affect docker installs, bare should continue to work.

Seat 5 upgrade instructions: Include steps how to upgrade custom styles

---

docs/configuration/eve_administrative_contact.md

In line with https://github.com/eveseat/web/pull/696

add email change restart docs
